#!/bin/bash
#
# Title:         Button Script
# Author:        b0n3z
# Version:       1.1
# Pineapple FW   2.1.0
#
# Turns off PineAP so it doesnt interfere with kismet
# Start Kismet on wlan0mon
# Start besside-ng on wlan1mon
#
# all led off then back on confirms both programs have started

# Variables
BS=/root/besside/
KM=/root/kismet/
PINE=/tmp/pineap.conf
SCREEN=/usr/sbin/screen

# Remove any previous logs from /root/ then
# make new directories
rm -r $BS
mkdir $BS
rm -r $KM
mkdir $KM
led yellow off
sleep 1

# Stop PineAP
pineap $PINE karma off
pineap $PINE capture_ssids off
pineap $PINE beacon_responses off
led red off
sleep 2

# kill dnsmasq to save resources
killall dnsmasq
led blue off
sleep 2

# Start wlan0 monitor mode
airmon-ng start wlan0
sleep 3
led yellow off

# Start kismet with wlan0mon
$SCREEN -dmS kismet bash -c 'cd $KM; kismet -c wlan0mon'
led blue on
sleep 1

# Start besside-ng with wlan1mon
$SCREEN -dmS besside-ng bash -c 'cd $BS; besside-ng wlan1mon'
led yellow on
sleep 3

# Show Script is started!!!

led red off
led yellow off
led blue off
sleep 3
led yellow on
led blue on
led red on

exit 0
